### PR TITLE
Standard go structure

### PR DESCRIPTION
**Pull request by giorgiozoppi**
-Changed the project structure to follow the community standard:
https://github.com/golang-standards/project-layout
Added a proper Makefile

### CODE REVIEW

**Review by feed3r — COMMENTED** [review]
It's ok for me, but I just would wait a comment from Dario to approve and merge to Main

**Review by DarioBalinzo — CHANGES_REQUESTED** [review]
I like the use of the standard project layout, but I suggest a little change:
mr-plow is a command line utility, not a library to share with others, for this reason we don't need the [pkg](https://github.com/golang-standards/project-layout/tree/master/pkg) folder (Library code that's ok to use by external applications), but probably the [internal](https://github.com/golang-standards/project-layout/tree/master/internal) folder (Private application and library code. This is the code you don't want others importing in their applications or libraries.)

**Comment by giorgiozoppi** [comment]
Guess now it's ok @DarioBalinzo

**Review by DarioBalinzo — APPROVED** [review]
lgtm! Thanks for you contribution @giorgiozoppi

**Comment by giorgiozoppi** [comment]
> lgtm! Thanks for you contribution @giorgiozoppi

@DarioBalinzo  you welcome.

**Pull request merged**
