### PR TITLE
- Remove test_util, it's not idiomatic looks like Java.

### PR DESCRIPTION
**Pull request by giorgiozoppi**
- inserted test package testify.
- pending to integrate with elastic.

	modified:   ../go.mod
	modified:   ../go.sum
	modified:   complete_config_test.go
	modified:   config_test.go
	modified:   insert_integration_test.go
	modified:   invalid_config_test.go
	modified:   scheduling_integration_test.go
	modified:   upsert_integration_test.go
	deleted:    ../test_util/test_util.go

### CODE REVIEW

**Comment by giorgiozoppi** [comment]
I put in draft because i should check with an EC2 instance and elastic since i work on WSL now. Tomorrow i give it  clue...i have also to understand how logstash works..

**Comment by giorgiozoppi** [comment]
Also tests doesnt' follow How to write code guidelines.

**Comment by DarioBalinzo** [comment]
Thank you for the suggestion! I will take a look soon..

Regarding logstash, I suggest to look at this jdbc input plugin to have an idea: https://www.elastic.co/guide/en/logstash/current/plugins-inputs-jdbc.html

**Comment by giorgiozoppi** [comment]
Thanks I will check, we need to meet us for a design session, there's a need of abstraction for different inject sources (i.e. netflow, syslog, no-sysql.) but before  introducing complexity ..we might need to think better how to modularize what we've.

**Comment by giorgiozoppi** [comment]
We close this since it was included in the last one

**Pull request closed without merging**
